require: 
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/*'
    - 'script/*'
    - 'bin/*'
    - 'node_modules/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'
    - config/initializers/*
    - config/environments/*

Metrics/LineLength:
  Max: 145
  Exclude:
    - config/initializers/*

Style/Documentation:
  Enabled: false

Style/Semicolon:
  Enabled: false  

Style/MixinUsage:  
  Enabled: false  

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*
    - spec/views/**/*

RSpec/MessageChain:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  Enabled: false
